application: my-io-talk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /jank-busters-io
  static_dir: jank-busters-io

- url: /raf
  static_dir: raf

