try{
function i(b){throw b;}var k=void 0,l=!0,m=null,o=!1;function aa(b){return function(){return this[b]}}var r;function s(b,a,c){b=b.split(".");c=c||t;!(b[0]in c)&&c.execScript&&c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)!b.length&&ba(a)?c[d]=a:c=c[d]?c[d]:c[d]={}}function ca(b){b.k=function $(){return b.jb?b.jb:b.jb=new b}}
function da(b){var a=typeof b;if("object"==a)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return a;var c=Object.prototype.toString.call(b);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==a&&"undefined"==typeof b.call)return"object";return a}function ba(b){return b!==k}function ea(b){return"array"==da(b)}function u(b){var a=da(b);return"array"==a||"object"==a&&"number"==typeof b.length}function w(b){return"string"==typeof b}function fa(b){return"function"==da(b)}function ga(b){return b[ha]||(b[ha]=++ia)}function ja(b,a,c){return b.call.apply(b.bind,arguments)}
function ka(b,a,c){b||i(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return b.apply(a,c)}}return function(){return b.apply(a,arguments)}}function x(b,a,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return x.apply(m,arguments)}
function y(b,a){function c(){}c.prototype=a.prototype;b.H=a.prototype;b.prototype=new c;b.prototype.constructor=b}function z(b){Error.captureStackTrace?Error.captureStackTrace(this,z):this.stack=Error().stack||"";b&&(this.message=""+b)}function A(b,a){return 0<=la(b,a)}function ma(b,a){var c=la(b,a),d;(d=0<=c)&&D.splice.call(b,c,1);return d}function na(b){var a=b.length;if(0<a){for(var c=Array(a),d=0;d<a;d++)c[d]=b[d];return c}return[]}
function oa(b,a){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(ea(d)||(e=u(d))&&d.hasOwnProperty("callee"))b.push.apply(b,d);else if(e)for(var f=b.length,g=d.length,h=0;h<g;h++)b[f+h]=d[h];else b.push(d)}}function pa(b,a){for(var c=a||b,d={},e=0,f=0;f<b.length;){var g=b[f++],h=typeof g,h="object"==h&&g!=m||"function"==h?"o"+ga(g):(typeof g).charAt(0)+g;Object.prototype.hasOwnProperty.call(d,h)||(d[h]=l,c[e++]=g)}c.length=e}
function qa(b){var a=[],c=0,d;for(d in b)a[c++]=b[d];return a}function ra(){return t.navigator?t.navigator.userAgent:m}function E(){}function F(b){b&&"function"==typeof b.N&&b.N()}function sa(b){for(var a=0,c=arguments.length;a<c;++a){var d=arguments[a];u(d)?sa.apply(m,d):F(d)}}function ta(b,a){this.b=[];this.i=a||m}function ua(b,a,c){b.ia=l;b.d=c;b.ka=!a;va(b)}function wa(b){b.ia&&(b.sb||i(new xa(b)),b.sb=o)}function ya(b,a,c,d){b.b.push([a,c,d]);b.ia&&va(b);return b}
function za(b){return Aa(b.b,function(a){return fa(a[1])})}
function va(b){b.f&&(b.ia&&za(b))&&(t.clearTimeout(b.f),delete b.f);b.g&&(b.g.Ob--,delete b.g);for(var a=b.d,c=o,d=o;b.b.length&&0==b.qa;){var e=b.b.shift(),f=e[0],g=e[1],e=e[2];if(f=b.ka?g:f)try{var h=f.call(e||b.i,a);ba(h)&&(b.ka=b.ka&&(h==a||h instanceof Error),b.d=a=h);a instanceof ta&&(d=l,b.qa++)}catch(j){a=j,b.ka=l,za(b)||(c=l)}}b.d=a;d&&b.qa&&(ya(a,x(b.bb,b,l),x(b.bb,b,o)),a.Pb=l);c&&(b.f=t.setTimeout(function(){i(new Ba(a))},0))}function xa(){z.call(this)}
function Ba(b){z.call(this);this.message="Unhandled Error in Deferred: "+(b.message||"[No message]")}function Ca(b){return function(){i(Error(b))}}function Da(){}function Ea(b,a){this.eb=b;this.g=a;this.f=[];this.d=[];this.b=[]}function Fa(b,a){var c=new b.i;c.kc(a());b.pa=c;c=(c=!!Ga(b,b.b,a()))||!!Ga(b,b.f,a());c||(b.d.length=0);return c}function Ga(b,a,c){for(var b=[],d=0;d<a.length;d++)try{a[d].execute(c)}catch(e){b.push(e)}a.length=0;return b.length?b:m}
function G(){this.G={};this.f=[];this.d=[];this.b=[];this.i=[];this.m={};this.g=this.l=new Ea([],"")}function Ha(b){var a=0<b.f.length;a!=b.kb&&(Ia(b,a?"active":"idle"),b.kb=a);a=0<b.i.length;a!=b.ub&&(Ia(b,a?"userActive":"userIdle"),b.ub=a)}
function Ja(b,a,c,d){c||(b.va=0);for(var e=0;e<a.length;e++)b.G[a[e]].pa&&i(Error("p`"+a[e]));c=[];for(e=0;e<a.length;e++)c=c.concat(Ka(b,a[e]));pa(c);!b.Za&&1<c.length&&(e=c.shift(),b.b=La(c,function(a){return[a]}).concat(b.b),c=[e]);b.f=c;b.Za?b.d=a:b.d=na(c);Ha(b);a=x(b.lb.b,b.lb,na(c),b.G,m,x(b.cc,b),x(b.dc,b),!!d);(b=5E3*Math.pow(b.va,2))?window.setTimeout(a,b):a()}
function Ka(b,a){for(var c=[a],d=na(b.G[a].eb);d.length;){var e=d.pop();b.G[e].pa||(c.unshift(e),Array.prototype.unshift.apply(d,b.G[e].eb))}pa(c);return c}function Ma(b,a){1<b.d.length?b.b=La(b.d,function(a){return[a]}).concat(b.b):Na(b,a)}
function Na(b,a){var c=b.d;b.f.length=0;for(var d=[],e=0;e<b.b.length;e++){var f=Oa(b.b[e],function(a){var b=Ka(this,a);return Aa(c,function(a){return A(b,a)})},b);oa(d,f)}for(e=0;e<c.length;e++){var f=d,g=c[e];A(f,g)||f.push(g)}for(e=0;e<d.length;e++){for(f=0;f<b.b.length;f++)ma(b.b[f],d[e]);ma(b.i,d[e])}if(g=b.m.error)for(e=0;e<g.length;e++)for(var h=g[e],f=0;f<d.length;f++)h("error",d[f],a);for(e=0;e<c.length;e++)b.G[c[e]]&&(d=b.G[c[e]],(f=Ga(d,d.d,a))&&window.setTimeout(Ca("Module errback failures: "+
f),0),d.b.length=0,d.f.length=0);b.d.length=0;Ha(b)}function Pa(b){for(;b.b.length;){var a=Oa(b.b.shift(),function(a){return!this.G[a].pa},b);if(0<a.length){Ja(b,a);return}}Ha(b)}function Ia(b,a){for(var c=b.m[a],d=0;c&&d<c.length;d++)c[d](a)}var t=this,ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0,H=Date.now||function(){return+new Date};
y(z,Error);z.prototype.name="CustomError";var D=Array.prototype,la=D.indexOf?function(b,a,c){return D.indexOf.call(b,a,c)}:function(b,a,c){c=c==m?0:0>c?Math.max(0,b.length+c):c;if(w(b))return!w(a)||1!=a.length?-1:b.indexOf(a,c);for(;c<b.length;c++)if(c in b&&b[c]===a)return c;return-1},I=D.forEach?function(b,a,c){D.forEach.call(b,a,c)}:function(b,a,c){for(var d=b.length,e=w(b)?b.split(""):b,f=0;f<d;f++)f in e&&a.call(c,e[f],f,b)},Oa=D.filter?function(b,a,c){return D.filter.call(b,a,c)}:function(b,a,c){for(var d=b.length,e=[],f=0,g=w(b)?b.split(""):
b,h=0;h<d;h++)if(h in g){var j=g[h];a.call(c,j,h,b)&&(e[f++]=j)}return e},La=D.map?function(b,a,c){return D.map.call(b,a,c)}:function(b,a,c){for(var d=b.length,e=Array(d),f=w(b)?b.split(""):b,g=0;g<d;g++)g in f&&(e[g]=a.call(c,f[g],g,b));return e},Aa=D.some?function(b,a,c){return D.some.call(b,a,c)}:function(b,a,c){for(var d=b.length,e=w(b)?b.split(""):b,f=0;f<d;f++)if(f in e&&a.call(c,e[f],f,b))return l;return o},Qa=D.every?function(b,a,c){return D.every.call(b,a,c)}:function(b,a,c){for(var d=b.length, e=w(b)?b.split(""):b,f=0;f<d;f++)if(f in e&&!a.call(c,e[f],f,b))return o;return l};
var Ra="StopIteration"in t?t.StopIteration:Error("g");var Sa,Ta,Ua,Va;Va=Ua=Ta=Sa=o;var Wa;if(Wa=ra()){var Xa=t.navigator;Sa=0==Wa.indexOf("Opera");Ta=!Sa&&-1!=Wa.indexOf("MSIE");Ua=!Sa&&-1!=Wa.indexOf("WebKit");Va=!Sa&&!Ua&&"Gecko"==Xa.product}var Ya=Sa,J=Ta,Za=Va,ab=Ua,bb=t.navigator,cb=-1!=(bb&&bb.platform||"").indexOf("Mac"),db;
a:{var eb="",fb;if(Ya&&t.opera)var gb=t.opera.version,eb="function"==typeof gb?gb():gb;else if(Za?fb=/rv\:([^\);]+)(\)|;)/:J?fb=/MSIE\s+([^\);]+)(\)|;)/:ab&&(fb=/WebKit\/(\S+)/),fb)var hb=fb.exec(ra()),eb=hb?hb[1]:"";if(J){var ib,jb=t.document;ib=jb?jb.documentMode:k;if(ib>parseFloat(eb)){db=""+ib;break a}}db=eb}var kb=db;
E.prototype.I=o;E.prototype.N=function $a(){this.I||(this.I=l,this.v())};E.prototype.v=function $b(){this.C&&sa.apply(m,this.C);if(this.Wa)for(;this.Wa.length;)this.Wa.shift()()};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
r=ta.prototype;r.ia=o;r.ka=o;r.qa=0;r.sb=o;r.Pb=o;r.Ob=0;r.bb=function $c(a,c){ua(this,a,c);this.qa--;0==this.qa&&this.ia&&va(this)};r.Y=function $d(a){wa(this);ua(this,l,a)};r.Ub=function $e(a){wa(this);ua(this,o,a)};y(xa,z);xa.prototype.message="Already called";y(Ba,z);
y(Da,E);Da.prototype.kc=function $f(){};y(Ea,E);Ea.prototype.i=Da;Ea.prototype.pa=m;Ea.prototype.getId=aa("g");Ea.prototype.v=function $h(){Ea.H.v.call(this);F(this.pa)};y(G,E);ca(G);r=G.prototype;r.Za=o;r.lb=m;r.va=0;r.kb=o;r.ub=o;r.pc=m;r.tc=function $i(a,c){if(w(a)){for(var d=a.split("/"),e=[],f=0;f<d.length;f++){var g=d[f].split(":"),h=g[0];if(g[1])for(var g=g[1].split(","),j=0;j<g.length;j++)g[j]=e[parseInt(g[j],36)];else g=[];e.push(h);this.G[h]=new Ea(g,h)}c&&oa(this.f,c);this.g==this.l&&(this.g=m,Fa(this.l,x(this.gb,this))&&Na(this,4))}};r.gb=aa("pc");
r.cc=function $k(a){this.va++;401==a?(Na(this,0),this.b.length=0):410==a?(Ma(this,3),Pa(this)):3<=this.va?(Ma(this,1),Pa(this)):Ja(this,this.d,l,8001==a)};r.dc=function $l(){Ma(this,2);Pa(this)};r.v=function $m(){G.H.v.call(this);I(qa(this.G),F);this.m=this.b=this.i=this.d=this.f=this.G=m};
s("_DumpException",function(b){b.errsource=b.errsource||"plusone_publisher";i(b)},k);var lb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),mb=ab;
var _ModuleManager_initialize=x(G.prototype.tc,G.k());
_ModuleManager_initialize('p1b/sy2/sy1:1/sy0:2/p1inl:3/sy6:2/sy5:3,5/sy7:6/p1p:7/psb:6/p1p_test:7/p1inl_test:4/p1_manual_inline_test:4/sy10:1/p1_iframe_test_case:5,d/p1_inline_test_case:d',['sy2','sy1','sy0','sy6','sy5','sy7','p1p']);
}catch(e){_DumpException(e)}
try{
function K(b){!b.g||b.g.getId();b.g=m}function L(b,a){b.g=b.G[a]}function M(b,a){b.I||(Fa(b.G[a],x(b.gb,b))&&Na(b,4),ma(b.i,a),ma(b.f,a),0==b.f.length&&Pa(b),Ha(b))}function nb(b){return b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ob(b){return pb[b]||(pb[b]=J&&!!document.documentMode&&document.documentMode>=b)}
function N(b){var a;if(!(a=qb[b])){a=0;for(var c=nb(""+kb).split("."),d=nb(""+b).split("."),e=Math.max(c.length,d.length),f=0;0==a&&f<e;f++){var g=c[f]||"",h=d[f]||"",j=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=j.exec(g)||["","",""],q=n.exec(h)||["","",""];if(0==p[0].length&&0==q[0].length)break;a=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<(0== q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==a)}a=qb[b]=0<=a}return a}var pb={},qb={};L(G.k(),"sy2");
!J||ob(9);!Za&&!J||J&&ob(9)||Za&&N("1.9.1");J&&N("9");
M(G.k(),"sy2");K(G.k(),"sy2");
}catch(e){_DumpException(e)}
try{
function rb(b,a){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)b[c]=d[c];for(var f=0;f<tb.length;f++)c=tb[f],Object.prototype.hasOwnProperty.call(d,c)&&(b[c]=d[c])}}function ub(b){ub[" "](b);return b}function O(b,a){this.type=b;this.b=this.target=a}var tb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");L(G.k(),"sy1");
ub[" "]=function $n(){};var vb=!J||ob(9),wb=!J||ob(9),xb=J&&!N("8");!ab||N("528");Za&&N("1.9b")||J&&N("8")||Ya&&N("9.5")||ab&&N("528");Za&&!N("8")||J&&N("9");y(O,E);O.prototype.v=function $o(){delete this.type;delete this.target;delete this.b};O.prototype.d=o;O.prototype.f=l;O.prototype.Oa=function $p(){this.f=o};
M(G.k(),"sy1");K(G.k(),"sy1");
}catch(e){_DumpException(e)}
try{
function yb(b,a,c,d){if(!d.Ba&&d.mb){for(var e=0,f=0;e<d.length;e++)d[e].da?d[e].d.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.mb=o;0==f&&(delete P[b][a][c],P[b][a].n--,0==P[b][a].n&&(delete P[b][a],P[b].n--),0==P[b].n&&delete P[b])}}
function zb(b){if(!Ab[b])return o;var a=Ab[b];if(a.da)return o;var c=a.src,d=a.type,e=a.d,f=a.capture;c.removeEventListener?(c==t||!c.cb)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Bb?Bb[d]:Bb[d]="on"+d,e);c=ga(c);e=P[d][f][c];if(Q[c]){var g=Q[c];ma(g,a);0==g.length&&delete Q[c]}a.da=l;e.mb=l;yb(d,f,c,e);delete Ab[b];return l}function Cb(b,a){b.ab&&zb(b.key);return b.handleEvent(a)}
function Db(b,a,c,d,e){var f=1,a=ga(a);if(b[a]){b.J--;b=b[a];b.Ba?b.Ba++:b.Ba=1;try{for(var g=b.length,h=0;h<g;h++){var j=b[h];j&&!j.da&&(f&=Cb(j,e)!==o)}}finally{b.Ba--,yb(c,d,a,b)}}return Boolean(f)}function Eb(b,a){b&&this.init(b,a)}function Fb(b,a){for(var c=b.split("."),d=a||t,e;e=c.shift();)if(d[e]!=m)d=d[e];else return m;return d}
function Gb(b,a){if(!Ab[b])return l;var c=Ab[b],d=c.type,e=P;if(!(d in e))return l;var e=e[d],f,g;if(!wb){f=a||Fb("window.event");var h=l in e,j=o in e;if(h){if(0>f.keyCode||f.returnValue!=k)return l;a:{var n=o;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(p){n=l}if(n||f.returnValue==k)f.returnValue=l}}n=new Eb;n.init(f,this);f=l;try{if(h){for(var q=[],v=n.b;v;v=v.parentNode)q.push(v);g=e[l];g.J=g.n;for(var C=q.length-1;!n.d&&0<=C&&g.J;C--)n.b=q[C],f&=Db(g,q[C],d,l,n);if(j){g=e[o];g.J=g.n;for(C=
0;!n.d&&C<q.length&&g.J;C++)n.b=q[C],f&=Db(g,q[C],d,o,n)}}else f=Cb(c,n)}finally{q&&(q.length=0),n.N()}return f}d=new Eb(a,this);try{f=Cb(c,d)}finally{d.N()}return f}function Hb(){}function Ib(b,a,c,d,e){if(ea(a)){for(var f=0;f<a.length;f++)Ib(b,a[f],c,d,e);return m}d=!!d;a:{f=P;if(a in f&&(f=f[a],d in f&&(f=f[d],b=ga(b),f[b]))){b=f[b];break a}b=m}if(!b)return o;for(f=0;f<b.length;f++)if(b[f].na==c&&b[f].capture==d&&b[f].Qa==e)return zb(b[f].key);return o}
function Jb(b,a,c,d,e){if(a){if(ea(a)){for(var f=0;f<a.length;f++)Jb(b,a[f],c,d,e);return m}var d=!!d,g=P;a in g||(g[a]={n:0,J:0});g=g[a];d in g||(g[d]={n:0,J:0},g.n++);var g=g[d],h=ga(b),j;g.J++;if(g[h]){j=g[h];for(f=0;f<j.length;f++)if(g=j[f],g.na==c&&g.Qa==e){if(g.da)break;return j[f].key}}else j=g[h]=[],g.n++;var n=Gb,p=wb?function(a){return n.call(p.src,p.key,a)}:function(a){a=n.call(p.src,p.key,a);if(!a)return a},f=p;f.src=b;g=new Hb;g.init(c,f,b,a,d,e);c=g.key;f.key=c;j.push(g);Ab[c]=g;Q[h]||
(Q[h]=[]);Q[h].push(g);b.addEventListener?(b==t||!b.cb)&&b.addEventListener(a,f,d):b.attachEvent(a in Bb?Bb[a]:Bb[a]="on"+a,f);return c}i(Error("A"))}function Kb(){}
function Lb(b,a){var c,d,e,f;c=a||document;if(c.querySelectorAll&&c.querySelector)c=c.querySelectorAll("."+b);else if(c.getElementsByClassName)c=c.getElementsByClassName(b);else if(c=a||document,c.querySelectorAll&&c.querySelector&&b)c=c.querySelectorAll(""+(b?"."+b:""));else if(b&&c.getElementsByClassName){var g=c.getElementsByClassName(b);c=g}else if(g=c.getElementsByTagName("*"),b){f={};for(d=e=0;c=g[d];d++){var h=c.className;"function"==typeof h.split&&A(h.split(/\s+/),b)&&(f[e++]=c)}f.length=
e;c=f}else c=g;return c}function Mb(b){if(mb){mb=o;var a=t.location;if(a){var c=a.href;if(c&&(c=(c=Mb(c)[3]||m)&&decodeURIComponent(c))&&c!=a.hostname)mb=l,i(Error())}}return b.match(lb)}function Nb(b){var a=[],c=0,d;for(d in b)a[c++]=d;return a}function Ob(b,a){return Object.prototype.hasOwnProperty.call(b,a)}function Pb(b,a){return b===a}
function Qb(b){if("function"==typeof b.U)return b.U();if("function"!=typeof b.F){if(u(b)||w(b)){for(var a=[],b=b.length,c=0;c<b;c++)a.push(c);return a}return Nb(b)}}function Rb(b){if("function"==typeof b.F)return b.F();if(w(b))return b.split("");if(u(b)){for(var a=[],c=b.length,d=0;d<c;d++)a.push(b[d]);return a}return qa(b)}function Sb(){}function Tb(b){b=b.charCodeAt(0);return"%"+(b>>4&15).toString(16)+(b&15).toString(16)}
function Ub(b,a){this.p={};this.b=[];var c=arguments.length;if(1<c){c%2&&i(Error("k"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else b&&this.Ja(b)}function Vb(b){if(b.n!=b.b.length){for(var a=0,c=0;a<b.b.length;){var d=b.b[a];Ob(b.p,d)&&(b.b[c++]=d);a++}b.b.length=c}if(b.n!=b.b.length){for(var e={},c=a=0;a<b.b.length;)d=b.b[a],Ob(e,d)||(b.b[c++]=d,e[d]=1),a++;b.b.length=c}}
function Wb(b,a,c){if("function"==typeof b.forEach)b.forEach(a,c);else if(u(b)||w(b))I(b,a,c);else for(var d=Qb(b),e=Rb(b),f=e.length,g=0;g<f;g++)a.call(c,e[g],d&&d[g],b)}function Xb(b){return D.concat.apply(D,arguments)}function Yb(b,a,c){return 2>=arguments.length?D.slice.call(b,a):D.slice.call(b,a,c)}function Zb(b,a,c){this.b=b||m;this.d=!!c}
function ac(b){if(!b.w&&(b.w=new Ub,b.n=0,b.b))for(var a=b.b.split("&"),c=0;c<a.length;c++){var d=a[c].indexOf("="),e=m,f=m;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];e=decodeURIComponent(e.replace(/\+/g," "));e=bc(b,e);cc(b,e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}function cc(b,a,c){ac(b);b.b=m;var a=bc(b,a),d=b.w.get(a);d||b.w.set(a,d=[]);d.push(c);b.n++;return b}function dc(b,a){ac(b);a=bc(b,a);return Ob(b.w.p,a)}
function bc(b,a){var c=""+a;b.d&&(c=c.toLowerCase());return c}function ec(b,a){return w(b)?encodeURI(b).replace(a,Tb):m}function fc(b,a,c){if(ea(a))for(var d=0;d<a.length;d++)fc(b,""+a[d],c);else a!=m&&c.push("&",b,""===a?"":"=",encodeURIComponent(""+a))}function gc(b){b=b.className;return w(b)&&b.match(/\S+/g)||[]}
function hc(b,a){var c;if(b instanceof hc)this.V=ba(a)?a:b.V,ic(this,b.ea),c=b.Fa,R(this),this.Fa=c,c=b.ja,R(this),this.ja=c,jc(this,b.Da),c=b.za,R(this),this.za=c,kc(this,b.b.P()),c=b.ya,R(this),this.ya=c;else if(b&&(c=Mb(""+b))){this.V=!!a;ic(this,c[1]||"",l);var d=c[2]||"";R(this);this.Fa=d?decodeURIComponent(d):"";d=c[3]||"";R(this);this.ja=d?decodeURIComponent(d):"";jc(this,c[4]);d=c[5]||"";R(this);this.za=d?decodeURIComponent(d):"";kc(this,c[6]||"",l);c=c[7]||"";R(this);this.ya=c?decodeURIComponent(c):
""}else this.V=!!a,this.b=new Zb(m,m,this.V)}function ic(b,a,c){R(b);b.ea=c?a?decodeURIComponent(a):"":a;b.ea&&(b.ea=b.ea.replace(/:$/,""));return b}function jc(b,a){R(b);a?(a=Number(a),(isNaN(a)||0>a)&&i(Error("r`"+a)),b.Da=a):b.Da=m;return b}
function kc(b,a,c){R(b);if(a instanceof Zb){b.b=a;a=b.b;if((c=b.V)&&!a.d)ac(a),a.b=m,Wb(a.w,function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),this.remove(c),0<a.length&&(this.b=m,this.w.set(bc(this,c),na(a)),this.n+=a.length))},a);a.d=c}else c||(a=ec(a,lc)),b.b=new Zb(a,m,b.V);return b}function R(b){b.mc&&i(Error("s"))}function mc(b,a){for(var c in a)fc(c,a[c],b);return b}
function nc(b){if(b[1]){var a=b[0],c=a.indexOf("#");0<=c&&(b.push(a.substr(c)),b[0]=a=a.substr(0,c));c=a.indexOf("?");0>c?b[1]="?":c==a.length-1&&(b[1]=k)}return b.join("")}function S(b){this.Va=b;this.S=[]}function oc(b,a,c,d,e,f){ea(c)||(pc[0]=c,c=pc);for(var g=0;g<c.length;g++)b.S.push(Jb(a,c[g],d||b,e||o,f||b.Va||b));return b}function qc(b){var a=da(b);if("object"==a||"array"==a){if(b.P)return b.P();var a="array"==a?[]:{},c;for(c in b)a[c]=qc(b[c]);return a}return b}function rc(b){this.b=b}
function sc(b){this.b=b}function tc(b){this.b=b}function uc(b){this.b=b}function vc(b){this.b=b}function wc(b,a){this.f=b||m;this.d=a||m;this.b=1}function xc(b,a,c){if(!c||c==b.b)b.d=a,b.b++,b.dispatchEvent("change")}function yc(b,a,c){!c||c==b.b?(b.d=m,b.b++,b.f=a,b.dispatchEvent("change")):(b.f=a,b.d||b.dispatchEvent("change"))}function zc(){this.d=[]}function Ac(b,a){return!(1<=b.b)?(a(),0):!(1<=b.d.length)?(b.d.push(a),1):2}
function Bc(b){this.f={};this.g={};this.d=(b||window.googleapis).plusones}function Cc(b,a){b.g[a]||(b.g[a]=new zc);return b.g[a]}function Dc(b,a){a.transport={name:"wrapped_googleapis",execute:x(b.i,b,a.transport)};return a}function Ec(b,a){switch(a.method){case "pos.plusones.get":return new uc(b);case "pos.plusones.insert":return new vc(b);case "pos.plusones.delete":return new tc(b);default:return new rc(b)}}
function Fc(b,a,c){a||(a={});var d=c||window,c="undefined"!=typeof b.href?b.href:""+b,b=a.target||b.target,e=[],f;for(f in a)switch(f){case "width":case "height":case "top":case "left":e.push(f+"="+a[f]);break;case "target":case "noreferrer":break;default:e.push(f+"="+(a[f]?1:0))}f=e.join(",");if(a.noreferrer){if(a=d.open("",b,f))J&&-1!=c.indexOf(";")&&(c="'"+c.replace(/'/g,"%27")+"'"),a.opener=m,ab?a.location.href=c:(Gc.test(c)&&(-1!=c.indexOf("&")&&(c=c.replace(Hc,"&amp;")),-1!=c.indexOf("<")&&
(c=c.replace(Ic,"&lt;")),-1!=c.indexOf(">")&&(c=c.replace(Jc,"&gt;")),-1!=c.indexOf('"')&&(c=c.replace(Kc,"&quot;"))),a.document.write('<META HTTP-EQUIV="refresh" content="0; url='+c+'">'),a.document.close())}else a=d.open(c,b,f);return a}function Lc(){}function Mc(){this.b={}}
function Nc(b,a,c,d){b=b||window;"number"!=typeof c&&(c=800);"number"!=typeof d&&(d=600);var e=b.outerHeight!=m?b.outerHeight:b.document.documentElement.clientHeight,f=b.screenY!=m?b.screenY:b.screenTop,b=Math.max(0,(b.screenX!=m?b.screenX:b.screenLeft)+((b.outerWidth!=m?b.outerWidth:b.document.documentElement.clientWidth)>>1)-(c>>1)),e=Math.max(0,f+(e>>1)-(d>>1)),c={left:b,top:e,menubar:o,toolbar:o,location:o,status:l,scrollbars:l,width:c,height:d};a&&(c.target=a);return c}
function Oc(b,a){this.z=b;this.S="GooglePlusPopupSignup";this.l="https://plus.google.com";this.D=""+Math.floor(1E9*Math.random());this.q=window.location.protocol+"//"+window.location.host;this.m=m;this.f=new ta;this.I=a;this.C=[1100,850];this.g=o}function Pc(b,a){a.match(/.*\/$/)&&(a=a.substr(0,a.length-1));b.l=a;return b}
function Qc(b,a){var c=b.l+"/_/+1/messageproxy";if(!b.u){var d=document.createElement("div");d.style.position="absolute";d.style.left="-1000px";d.style.top="-1000px";d.style.width="1px";d.style.height="1px";document.body.appendChild(d);b.u=iframes.open(c,{container:d},{},{handleMessage:x(b.A,b)})}c=b.l+"/+1/profile/?type=po&client="+b.I+"&gpsrc="+encodeURIComponent(b.z)+"&parent="+encodeURIComponent(b.q)+"&proxy="+b.u.getId();b.m&&(c+="&continue="+encodeURIComponent(b.m));b.g&&(c+="&rsz=1");c+=(!window.__P1_LOCALE?
"":"&hl="+window.__P1_LOCALE)+"#"+b.D;(c=Fc(c,Nc(a,b.S,b.C[0],b.C[1])))&&c.focus();return c}function Rc(b){return Fc("https://www.google.com/support/profiles/?p=plusone_button_error&hl=en-US",Nc(b||window,"GooglePlusOneHelp",800,600))}var P={},Bb={},Q={},Ab={},Sc=0;y(Eb,O);r=Eb.prototype;r.target=m;r.relatedTarget=m;r.clientX=0;r.clientY=0;r.button=0;r.keyCode=0;r.ctrlKey=o;r.ha=m;
r.init=function $q(a,c){var d=this.type=a.type;O.call(this,d);this.target=a.target||a.srcElement;this.b=c;var e=a.relatedTarget;if(e){if(Za){var f;a:{try{ub(e.nodeName);f=l;break a}catch(g){}f=o}f||(e=m)}}else"mouseover"==d?e=a.fromElement:"mouseout"==d&&(e=a.toElement);this.relatedTarget=e;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.button=a.button;this.keyCode=a.keyCode||0;this.ctrlKey=a.ctrlKey;this.state=a.state;this.ha=a;a.defaultPrevented&&
this.Oa();delete this.d};r.Oa=function $r(){Eb.H.Oa.call(this);var a=this.ha;if(a.preventDefault)a.preventDefault();else if(a.returnValue=o,xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(c){}};r.v=function $s(){Eb.H.v.call(this);this.relatedTarget=this.b=this.target=this.ha=m};r=Hb.prototype;r.key=0;r.da=o;r.ab=o;
r.init=function $t(a,c,d,e,f,g){fa(a)?this.b=l:a&&a.handleEvent&&fa(a.handleEvent)?this.b=o:i(Error("z"));this.na=a;this.d=c;this.src=d;this.type=e;this.capture=!!f;this.Qa=g;this.ab=o;this.key=++Sc;this.da=o};r.handleEvent=function $u(a){return this.b?this.na.call(this.Qa||this.src,a):this.na.handleEvent.call(this.na,a)};y(Kb,E);r=Kb.prototype;r.cb=l;r.Ra=m;r.addEventListener=function $v(a,c,d,e){Jb(this,a,c,d,e)};r.removeEventListener=function $w(a,c,d,e){Ib(this,a,c,d,e)};
r.dispatchEvent=function $x(a){var c=a.type||a,d=P;if(c in d){if(w(a))a=new O(a,this);else if(a instanceof O)a.target=a.target||this;else{var e=a,a=new O(c,this);rb(a,e)}var e=1,f,d=d[c],c=l in d,g;if(c){f=[];for(g=this;g;g=g.Ra)f.push(g);g=d[l];g.J=g.n;for(var h=f.length-1;!a.d&&0<=h&&g.J;h--)a.b=f[h],e&=Db(g,f[h],a.type,l,a)&&a.f!=o}if(o in d)if(g=d[o],g.J=g.n,c)for(h=0;!a.d&&h<f.length&&g.J;h++)a.b=f[h],e&=Db(g,f[h],a.type,o,a)&&a.f!=o;else for(f=this;!a.d&&f&&g.J;f=f.Ra)a.b=f,e&=Db(g,f,a.type,
o,a)&&a.f!=o;a=Boolean(e)}else a=l;return a};r.v=function $z(){Kb.H.v.call(this);var a=k,c=0,d=this==m,e=a==m,a=!!a;if(d){var d=function $y(d){for(var f=d.length-1;0<=f;f--){var g=d[f];if(e||a==g.capture)zb(g.key),c++}},f;for(f in Q)d.call(k,Q[f],f,Q)}else if(f=ga(this),Q[f]){f=Q[f];for(d=f.length-1;0<=d;d--){var g=f[d];if(e||a==g.capture)zb(g.key),c++}}this.Ra=m};Sb.prototype.next=function $A(){i(Ra)};Sb.prototype.Ia=function $B(){return this};r=Ub.prototype;r.n=0;r.Ga=0;r.O=aa("n");
r.F=function $D(){Vb(this);for(var a=[],c=0;c<this.b.length;c++)a.push(this.p[this.b[c]]);return a};r.U=function $E(){Vb(this);return this.b.concat()};r.wa=function $F(a){for(var c=0;c<this.b.length;c++){var d=this.b[c];if(Ob(this.p,d)&&this.p[d]==a)return l}return o};r.Na=function $G(a,c){if(this===a)return l;if(this.n!=a.O())return o;var d=c||Pb;Vb(this);for(var e,f=0;e=this.b[f];f++)if(!d(this.get(e),a.get(e)))return o;return l};
r.remove=function $H(a){return Ob(this.p,a)?(delete this.p[a],this.n--,this.Ga++,this.b.length>2*this.n&&Vb(this),l):o};r.get=function $I(a,c){return Ob(this.p,a)?this.p[a]:c};r.set=function $J(a,c){Ob(this.p,a)||(this.n++,this.b.push(a),this.Ga++);this.p[a]=c};r.Ja=function $K(a){var c;a instanceof Ub?(c=a.U(),a=a.F()):(c=Nb(a),a=qa(a));for(var d=0;d<c.length;d++)this.set(c[d],a[d])};r.P=function $L(){return new Ub(this)};
r.Ia=function $N(a){Vb(this);var c=0,d=this.b,e=this.p,f=this.Ga,g=this,h=new Sb;h.next=function $M(){for(;;){f!=g.Ga&&i(Error("l"));c>=d.length&&i(Ra);var h=d[c++];return a?h:e[h]}};return h};r=Zb.prototype;r.w=m;r.n=m;r.O=function $O(){ac(this);return this.n};r.remove=function $P(a){ac(this);a=bc(this,a);return Ob(this.w.p,a)?(this.b=m,this.n-=this.w.get(a).length,this.w.remove(a)):o};r.wa=function $Q(a){var c=this.F();return A(c,a)};
r.U=function $R(){ac(this);for(var a=this.w.F(),c=this.w.U(),d=[],e=0;e<c.length;e++)for(var f=a[e],g=0;g<f.length;g++)d.push(c[e]);return d};r.F=function $S(a){ac(this);var c=[];if(a)dc(this,a)&&(c=Xb(c,this.w.get(bc(this,a))));else for(var a=this.w.F(),d=0;d<a.length;d++)c=Xb(c,a[d]);return c};r.set=function $T(a,c){ac(this);this.b=m;a=bc(this,a);dc(this,a)&&(this.n-=this.w.get(a).length);this.w.set(a,[c]);this.n++;return this};
r.get=function $U(a,c){var d=a?this.F(a):[];return 0<d.length?d[0]:c};r.toString=function $V(){if(this.b)return this.b;if(!this.w)return"";for(var a=[],c=this.w.U(),d=0;d<c.length;d++)for(var e=c[d],f=encodeURIComponent(""+e),e=this.F(e),g=0;g<e.length;g++){var h=f;""!==e[g]&&(h+="="+encodeURIComponent(""+e[g]));a.push(h)}return this.b=a.join("&")};r.P=function $W(){var a=new Zb;a.b=this.b;this.w&&(a.w=this.w.P());return a};
r.Zb=function $X(a){for(var c=0;c<arguments.length;c++)Wb(arguments[c],function(a,c){cc(this,c,a)},this)};var Tc=/#/g,lc=/[\#\?@]/g,Uc=/[\#\?]/g,Vc=/[\#\?:]/g,Wc=/[#\/\?@]/g,pc=[];r=hc.prototype;r.ea="";r.Fa="";r.ja="";r.Da=m;r.za="";r.ya="";r.mc=o;r.V=o;
r.toString=function $Y(){var a=[],c=this.ea;c&&a.push(ec(c,Wc),":");if(c=this.ja){a.push("//");var d=this.Fa;d&&a.push(ec(d,Wc),"@");a.push(encodeURIComponent(""+c));c=this.Da;c!=m&&a.push(":",""+c)}if(c=this.za)this.ja&&"/"!=c.charAt(0)&&a.push("/"),a.push(ec(c,"/"==c.charAt(0)?Uc:Vc));(c=this.b.toString())&&a.push("?",c);(c=this.ya)&&a.push("#",ec(c,Tc));return a.join("")};r.P=function $Z(){return new hc(this)};var Gc=/[&<>\"]/,Kc=/\"/g,Jc=/>/g,Ic=/</g,Hc=/&/g;y(S,E); S.prototype.Eb=function $_(){I(this.S,zb);this.S.length=0};S.prototype.v=function $0(){S.H.v.call(this);this.Eb()};S.prototype.handleEvent=function $1(){i(Error("B"))};L(G.k(),"sy0");
rc.prototype.f=function $2(a){return a};rc.prototype.g=function $3(a){return a};rc.prototype.d=0;rc.prototype.update=function $4(a,c){var d=this.b.b(a);!c||c.error||!c.result?xc(d,m,this.d):yc(d,c.result,this.d)};y(sc,rc);sc.prototype.f=function $5(a){var c=a.params,d=c&&c.optimistic,e=c&&c.id;this.m=e;var f=this.b.b(e).get(),g=f=f?qc(f):{id:e,isSetByViewer:o,metadata:{}},g=g||{};g.metadata=g.metadata||{};g.metadata.globalCounts=g.metadata.globalCounts||{};this.i(f,c);this.l=f;d&&(xc(this.b.b(e),f),a=qc(a),delete a.params.optimistic);this.d=this.b.b(e).b;return a};
sc.prototype.g=function $6(a){if(a.result){var c=a.result,d=this.l;c.metadata=c.metadata||d.metadata;c.metadata.globalCounts=c.metadata.globalCounts||d.metadata.globalCounts;c.metadata.globalCounts.count=c.metadata.globalCounts.count||d.metadata.globalCounts.count;if(d=c.metadata.globalCounts.person||d.metadata.globalCounts.person)c.metadata.globalCounts.person=d}this.update(this.m,a);return a};
y(tc,sc);tc.prototype.i=function $7(a){a.isSetByViewer&&a.metadata.globalCounts.count!=k&&(a.metadata.globalCounts.count=Math.max(a.metadata.globalCounts.count-1,0));a.isSetByViewer=o};y(uc,rc);uc.prototype.f=function $8(a){this.i=a.params&&a.params.id;this.d=this.b.b(this.i).b;return a};uc.prototype.g=function $9(a){this.update(this.i,a);return a};y(vc,sc);vc.prototype.i=function $$(a,c){!a.isSetByViewer&&a.metadata.globalCounts.count!=k&&a.metadata.globalCounts.count++;a.isSetByViewer=l;a.aclJson=c.aclJson};y(wc,Kb);wc.prototype.get=function $aa(){return this.d||this.f};zc.prototype.b=0;Bc.prototype.get=function $ba(a){return Dc(this,this.d.get(a))};Bc.prototype.remove=function $ca(a){return Dc(this,this.d.remove(a))};Bc.prototype.b=function $da(a){this.f[a]||(this.f[a]=new wc);return this.f[a]};
Bc.prototype.i=function $ea(a,c,d){for(var e={},f=[],g=[],h=0,j=c.length;h<j;++h){var n=c[h],p;p=n.method;var q=n.params,q=q&&q.id;if(p=("pos.plusones.insert"==p||"pos.plusones.delete"==p)&&q?Cc(this,q):m)p.b++,g.push(p);p=n.id;e[p]=Ec(this,n);(n=e[p].f(n))&&f.push(n)}a.execute(f,x(function(a){for(var c=0,f=g.length;c<f;++c){var h=g[c];for(h.b--;!(1<=h.b)&&h.d.length;)h.d.shift()()}var c={},j;for(j in e)(f=e[j].g(a[j]||m))&&(c[j]=f);d(c)},this))};
y(Oc,Lc);Oc.prototype.b=o;Oc.prototype.d=m;Oc.prototype.A=function $fa(a){try{var c=new Mc;c.b=Object(a);this.b=!!c.b.created;this.i=""+(c.b.version||"");this.f.Y(c)}catch(d){if(this.d)try{this.d(d)}catch(e){}this.f.Ub(d)}};
M(G.k(),"sy0");K(G.k(),"sy0");
}catch(e){_DumpException(e)}
try{
L(G.k(),"sy6");var td=t.window;
M(G.k(),"sy6");K(G.k(),"sy6");
}catch(e){_DumpException(e)}
try{
function ud(b){this.b=b||t.document||document}function vd(b){return b?new ud(9==b.nodeType?b:b.ownerDocument||b.document):wd||(wd=new ud)}function xd(b){return b.b.parentWindow||b.b.defaultView}function yd(b){if(zd[b])return zd[b];b=""+b;if(!zd[b]){var a=/function ([^\(]+)/.exec(b);zd[b]=a?a[1]:"[Anonymous]"}return zd[b]}function Ad(b,a){return b.b(a).get()}function Bd(b){if("function"==typeof b.O)b=b.O();else if(u(b)||w(b))b=b.length;else{var a=0,c;for(c in b)a++;b=a}return b}
function Cd(b){var a=typeof b;return"object"==a&&b||"function"==a?"o"+ga(b):a.substr(0,1)+b}function Dd(b,a){var c=Array.prototype.slice.call(arguments,1);return function(){var a=Array.prototype.slice.call(arguments);a.unshift.apply(a,c);return b.apply(this,a)}}function Ed(b){this.p=new Ub;b&&this.Ja(b)}function Fd(b,a){function c(){}c.prototype=b.prototype;var d=new c;b.apply(d,Array.prototype.slice.call(arguments,1));return d}
function Gd(b,a,c){for(c=c||0;c<a.length;c+=2)fc(a[c],a[c+1],b);return b}
function Hd(b,a){var c=[];if(A(a,b))c.push("[...circular reference...]");else if(b&&50>a.length){c.push(yd(b)+"(");for(var d=b.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=""+f;break;case "boolean":f=f?"true":"false";break;case "function":f=(f=yd(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}a.push(b);c.push(")\n");try{c.push(Hd(b.caller,a))}catch(g){c.push("[exception trying to get caller]\n")}}else b?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Id(b,a,c){fa(b)?c&&(b=x(b,c)):b&&"function"==typeof b.handleEvent?b=x(b.handleEvent,b):i(Error("z"));return 2147483647<a?-1:td.setTimeout(b,a||0)}
function Jd(b,a,c,d,e){a||(a=c?[c]:[]);b.b=a;b.d=[];if(e)for(a=0;a<e.length;a++)b.b[e[a]]=b.b[e[a]]||[];if(-1!=d){b.g={};a:{e=b.b;if(e.length&&(c=e.length-1,(a=e[c])&&"object"==typeof a&&"number"!=typeof a.length)){c<d&&(e[d]=a,delete e[c]);d=a;break a}a={};d=e[Math.max(e.length,d)]=a}b.f=d}}function Kd(){this.d=[]}function Ld(b){return b.b}function Md(b,a){return nc(2==arguments.length?Gd([b],arguments[1],0):Gd([b],arguments,1))}function Nd(b){return Hd(b||arguments.callee.caller,[])}
function Od(b){var a={},c;for(c in b)a[c]=b[c];return a}function Pd(b,a,c){for(var d=w(b)?b.split(""):b,e=b.length-1;0<=e;--e)e in d&&a.call(c,d[e],e,b)}function Qd(b){this.d=[];Jd(this,b,"",-1,[])}function Rd(b){this.d=[];Jd(this,b,"",-1,[0])}function Sd(){this.b=[]}function Td(b){var a=new Rd,b=(b=b.b)||[];a.d[0]=b;a.b[0]=[];for(var c=0;c<b.length;c++)a.b[0][c]=b[c].b;return a}function Ud(b){var a=Vd(b,"oa");a||(a=new Sd,Wd(b,"oa",a));return a}
function Xd(b,a,c){this.u=!!a.si;this.C=!!a.su;this.D=a.e||m;this.A=a.dn||m;this.i=a.a||m;this.g=a.at||m;this.q=!!a.aw;this.m=a.amw||m;this.l=!!a.ah;var d=a.ld;d&&(b=Ud(b),d=new Qd(d),b.b.push(d));this.z={id:a.id,isSetByViewer:!!a.is,metadata:{globalCounts:{count:a.c||0}}};this.b=c||{};this.d=a.s||"widget";this.f=a.r||m;this.I=!!a.h}function Yd(b){var a=Vd(b,"ha");a||(a=new Bc,Wd(b,"ha",a));return a}
function Zd(b,a,c){if(b&&!b.error)return"";if(b){var d="Error in RPC: "+b.id;b.error&&(d=b.error.message?d+(" - "+b.error.message):d+(" - "+b.error))}else d="Empty response";a&&a.call(c,d);return d}function ae(b){this.d={};this.l={};this.g={};this.b={};this.m={};this.u={};this.q=b?b.q:new Kb;this.A=!b;this.f=m;b?(this.f=b,this.g=b.g,this.b=b.b,this.l=b.l,this.m=b.m):H();b=be(this);this!=b&&(b.i?b.i.push(this):b.i=[this])}function be(b){for(;b.f;)b=b.f;return b}
function ce(b,a){for(var c=b;c;){if(c==a)return l;c=c.f}return o}function Vd(b,a){for(var c=b;c;c=c.f){if(c.d[a])return c.d[a][0];if(c.u[a])break}return(c=b.g[a])?(c=c(b),Wd(b,a,c),c):m}function Wd(b,a,c,d){if(b.I)d||F(c);else{b.d[a]=[c,!d];var e=[],f=b.b[a];f&&(Pd(f,function(a){ce(a.T,b)&&(e.push(a.Sb),ma(f,a))}),0==f.length&&delete b.b[a]);for(c=0;c<e.length;c++)e[c].Y(m);delete b.l[a]}}
function de(b,a){if(b.T!=a.T){if(ce(b.T,a.T))return 1;if(ce(a.T,b.T))return-1}return b.index<a.index?-1:b.index==a.index?0:1}function ee(b){z.call(this);this.id=b;this.message='Service for "'+b+'" is not registered'}function fe(b,a){this.d=b;this.b=a}function ge(b){he(b,"onstartinteraction");return b}function ie(b){he(b,"onendinteraction");return b}function he(b,a){if(iframer){var c=iframer[a];c&&c({type:b.d,id:b.b})}}
function je(b,a){var c=/^(\/u\/\d+)\//;return 0==b.lastIndexOf("/",0)&&!b.match(c)&&(c=((9==a.nodeType?a:a.ownerDocument||a.document)?(9==a.nodeType?a:a.ownerDocument||a.document).parentWindow||(9==a.nodeType?a:a.ownerDocument||a.document).defaultView:window).location.pathname.match(c))?c[1]+b:b}
function T(b,a,c,d,e,f,g,h,j,n,p){this.g=new fe(b,g);this.C=je(a,c);this.l={style:"bubble",bubbletype:"pls-default",arrowPosition:"center",anchorPosition:"center",anchor:c,height:50,width:d,closeClickDetection:l,hideClickDetection:!!n,maxExpectedSize:{height:400},showSpinner:l};if(p)for(var q in p)this.l[q]=p[q];this.f={hl:"en-US",url:g,t:h};j&&(this.f.source=j);document.documentMode&&(this.f.hostiemode=document.documentMode);this.i={mouseEvent:e,trackingEvent:f,onVisibilityChanged:x(this.u,this)};
iframer&&iframer.onshare&&(this.i.onshare=iframer.onshare)}function ke(b,a){b.b&&b.b.show&&b.b.show(a)}function le(b,a){if(!b.d)return m;var c=b.b;if(!c)return m;c=c[a];return!fa(c)?m:c}function me(b,a,c,d,e,f,g,h){T.call(this,"confirm","/_/+1/confirm",b,g||431,a,c,d,e,f,h,{startVisible:!!h})}function ne(b,a,c,d){this.b=je("/_/+1/confirm",b);this.f={menubar:o,resizable:l,toolbar:o,status:o,scrollbars:o,height:400,width:450};this.d={hl:"en-US",url:a,t:c,popup:l};d&&(this.d.source=d)}
function oe(b,a,c,d,e,f,g,h,j,n){T.call(this,"hover","/_/+1/hover",b,e?431:350,a,c,d,f,g,n);this.f.isSet=e;h&&(this.f.h=h);j&&(this.f.ad=j)}function pe(b,a,c,d,e,f,g,h,j,n,p,q,v){S.call(this);this.D=b;this.q=a;this.L=c;this.fa=d;this.sa=e;this.Ha=f;this.u=g;this.f=H();this.ga=!h;this.W=!j;this.ra=!n;this.A=!!p;this.ua=!!q;this.ta=!!v;if(this.ga||this.W)oc(this,b,"mouseover",this.gc),oc(this,b,"mouseout",this.fc)}
function qe(b,a){b.u&&(a.f.referer=b.u);a.l.expandTo=b.sa;!a.b&&!a.d&&(a.b=iframes.open(a.C,Od(a.l),Od(a.f),Od(a.i),x(a.q,a)),a.d=l,ge(a.g))}function re(b){var a=x(b.ob,b);if(!b.m&&b.W&&(!b.g||!b.g.d))b.b&&!b.b.d&&b.b.b?se(b,l):(b.i&&b.K(l),a=a(b.D,x(b.qb,b),b.fa,b.q,b.f,b.L,b.A),qe(b,a),b.b=b.g=a,b.z=b.Ma)}function se(b,a,c){b.b&&(ke(b.b,a),b.b.m(!!c))}function te(b){b.Z=l;b.l&&td.clearTimeout(b.l);b.l=Id(b.Qb,b.z,b)}function ue(){}
function ve(b,a,c){this.d=a||U.zb;this.L=c||0;this.i=40;this.b=1;this.I=3;this.l=this.f=0;this.S=o;this.A=this.z="";this.m="-";this.q="";this.g=1;this.C=3;this.u=this.D=o;if("number"==typeof b)switch(b){case 1:we(this,U.xb);break;case 2:we(this,U.Nb);break;case 3:we(this,U.Jb);break;case 4:b=U.wb;a=["0"];c=xe[this.d][0]&7;if(0<c){a.push(".");for(var d=0;d<c;d++)a.push("0")}b=b.replace(/0.00/g,a.join(""));we(this,b);break;default:i(Error("G"))}else we(this,b)}
function we(b,a){a.replace(/ /g,"\u00a0");var c=[0];b.z=ye(b,a,c);for(var d=c[0],e=-1,f=0,g=0,h=0,j=-1,n=a.length,p=l;c[0]<n&&p;c[0]++)switch(a.charAt(c[0])){case "#":0<g?h++:f++;0<=j&&0>e&&j++;break;case "0":0<h&&i(Error("I`"+a));g++;0<=j&&0>e&&j++;break;case ",":j=0;break;case ".":0<=e&&i(Error("J`"+a));e=f+g+h;break;case "E":b.u&&i(Error("K`"+a));b.u=l;b.l=0;c[0]+1<n&&"+"==a.charAt(c[0]+1)&&(c[0]++,b.S=l);for(;c[0]+1<n&&"0"==a.charAt(c[0]+1);)c[0]++,b.l++;(1>f+g||1>b.l)&&i(Error("L`"+a));p=o;break;
default:c[0]--,p=o}0==g&&(0<f&&0<=e)&&(g=e,0==g&&g++,h=f-g,f=g-1,g=1);(0>e&&0<h||0<=e&&(e<f||e>f+g)||0==j)&&i(Error("M`"+a));h=f+g+h;b.I=0<=e?h-e:0;0<=e&&(b.f=f+g-e,0>b.f&&(b.f=0));b.b=(0<=e?e:h)-f;b.u&&(b.i=f+b.b,0==b.I&&0==b.b&&(b.b=1));b.C=Math.max(0,j);b.D=0==e||e==h;d=c[0]-d;b.A=ye(b,a,c);c[0]<a.length&&";"==a.charAt(c[0])?(c[0]++,b.m=ye(b,a,c),c[0]+=d,b.q=ye(b,a,c)):(b.m=b.z+b.m,b.q+=b.A)}
function ze(b,a,c,d){var e=Math.pow(10,b.I),f=Math.round(a*e),g;isFinite(f)?(a=Math.floor(f/e),g=Math.floor(f-a*e)):g=0;for(var h=0<b.f||0<g,j="",f=a;1.0E20<f;)j="0"+j,f=Math.round(f/10);var j=f+j,n=U.yb,p=U.Bb,f=U.Xa.charCodeAt(0),q=j.length;if(0<a||0<c){for(a=q;a<c;a++)d.push(String.fromCharCode(f));for(a=0;a<q;a++)d.push(String.fromCharCode(f+1*j.charAt(a))),1<q-a&&(0<b.C&&1==(q-a)%b.C)&&d.push(p)}else h||d.push(String.fromCharCode(f));(b.D||h)&&d.push(n);c=""+(g+e);for(e=c.length;"0"==c.charAt(e-
1)&&e>b.f+1;)e--;for(a=1;a<e;a++)d.push(String.fromCharCode(f+1*c.charAt(a)))}function Ae(b,a,c){c.push(U.Ab);0>a?(a=-a,c.push(U.Db)):b.S&&c.push(U.Lb);for(var a=""+a,d=U.Xa,e=a.length;e<b.l;e++)c.push(d);c.push(a)}
function ye(b,a,c){for(var d="",e=o,f=a.length;c[0]<f;c[0]++){var g=a.charAt(c[0]);if("'"==g)c[0]+1<f&&"'"==a.charAt(c[0]+1)?(c[0]++,d+="'"):e=!e;else if(e)d+=g;else switch(g){case "#":case "0":case ",":case ".":case ";":return d;case "\u00a4":if(c[0]+1<f&&"\u00a4"==a.charAt(c[0]+1))c[0]++,d+=b.d;else switch(b.L){case 0:d+=xe[b.d][1];break;case 2:var g=b.d,h=xe[g],d=d+(g==h[1]?g:g+" "+h[1]);break;case 1:d+=xe[b.d][2]}break;case "%":1!=b.g&&i(Error("H"));b.g=100;d+=U.Ib;break;case "\u2030":1!=b.g&&
i(Error("H"));b.g=1E3;d+=U.Kb;break;default:d+=g}}return d}function Be(b){this.b=b}function Ce(b){for(var b=(b.b.cookie||"").split(De),a=[],c=[],d,e,f=0;e=b[f];f++)d=e.indexOf("="),-1==d?(a.push(""),c.push(e)):(a.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:a,vb:c}}function V(b){return"object"===typeof b&&b&&0===b.Ec?b.content:(""+b).replace(Ee,Fe)}function Fe(b){return Ge[b]}
function He(b){var a="";9<b.Q?a+="Lots of people +1'd this":6<b.Q?(b=V(b.count)+" million people +1'd this",a+=b):3<b.Q?(b=V(b.count)+" thousand people +1'd this",a+=b):1==b.count?a+="1 person +1'd this":(b=V(b.count)+" people +1'd this",a+=b);return a}function Ie(){}function Je(){}function Le(b){this.b=b}
function Me(b){S.call(this);var a=gadgets.util.getUrlParameters()||{};this.D=a;var c=Vd(b,"ia");this.Vb=x(c.hb,c);var d=b.get("la");this.f=d;this.X=!(a.db&&"1"==a.db);this.Mb=a.ecp&&"true"==a.ecp;this.q="string"==typeof a.ad&&"false"!=a.ad.toLowerCase();this.d=Yd(b);var e=b.get("na");this.i=e;gapi.config.update("googleapis.config/auth/useFirstPartyAuth",l);var c=e.z,f=c.id;this.g=f;var g=this.d.b(f);if(g){oc(this,g,"change",this.ba);this.Ha=b.get("ka");var h=xd(d);this.l=b.get("ja");this.Gb=new ve(1);
this.m=(d||vd()).R("button");this.ra=Ud(b);this.u=e.u;this.l.b=e.C;ya(this.l.f,this.Pa,m,this);b=e.A;this.ga=e.D||"";this.fa=b||"";Ne(this,Ad(this.d,f));this.sa=H();oc(this,h,"unload",this.N);b=x(this.Ca,this);Oe.b(this.m,b,k,this.Va||this,this);Pe(this)&&this.m.setAttribute("title","");this.Hb=!!e.I;if(a.expandTo){var j=[];I(a.expandTo.split(","),function(a){if((a=nb(a).toLowerCase())&&!A(j,a))A(Qe,a)||i(Error("F`"+a)),j.push(a)});a=j}else a=[];e=this.b=this.nb(this.m,this.g,e.d,x(this.qc,this),
a,this.d,e.f,!Pe(this),!Re(this),!(!this.X&&this.Mb&&this.i.b.UCP),this.Hb,this.q);this.C||(this.C=[]);this.C.push(e);yc(g,c);c=x(this.xc,this);s("SB_verify",c,k)}}
function Se(b){b=b||new ae;if(!Te){var a=function $ra(b){b.yc||(b.yc=l,b.aa&&I(b.aa.F(),a),j.push(b))},c={},d,e;for(d=Ue.length-1;0<=d;--d){var f=Ue[d];if(f.oa.b){var g=f.oa.b;for(e=g.length-1;0<=e;--e)c[g[e].id]=f}if(f.oa.i){g=f.oa.i;for(e=g.length-1;0<=e;--e)c[g[e].id]=f}}for(d=Ue.length-1;0<=d;--d){f=Ue[d];g=f.oa;if(g.d){f.aa=new Ed;for(e=g.d.length-1;0<=e;--e){var h=c[g.d[e]];h&&f.aa.p.set(Cd(h),h)}}if(g.f){f.aa||(f.aa=new Ed);for(e=g.f.length-1;0<=e;--e)(h=c[g.f[e]])&&f.aa.p.set(Cd(h),h)}}var j=
[];I(Ue,a);Ue=j;for(c=0;c<Ue.length;++c){d=Ue[c].oa;if(d.b){e=b;f=d.b;for(g=0;g<f.length;++g){var n=f[g];if(!e.d[n.id]&&!e.g[n.id]&&!n.Fc)if(n.oc)e.l[n.id]=n.oc;else if(n.multiple){var h=e,p=n.id,n=n.Y||Dd(Fd,n.Rb);h.g[p]=n;if(n=h.b[p]){if(1<n.length){for(var q=0;q<n.length;++q)n[q].index=q;n.sort(de)}for(;n.length;)n.shift().Sb.Y(m);delete h.b[p]}}else Wd(e,n.id,n.Y?n.Y(e):new n.Rb(e))}}d.g&&d.g(b)}for(c=0;c<Ue.length;++c);for(c=0;c<Ve.length;++c)Ve[c](b);Te=l}c=vd(document);Wd(b,"la",c);Wd(b,"ia",
new Le("/_/jserror"));d=new Xd(b,window.__SSR,window.__P1_XP);Wd(b,"na",d);"only"!=d.i&&Wd(b,"ka",new Be(c.b));return b}function We(b,a){var c=a||{};c.id=b.g;c.source=b.i.d;c.track=gadgets.json.stringify(Ld(Td(b.ra)));var d=b.i.f;d&&(c.container=d);return c}
function Xe(b,a){if(a&&a.metadata&&a.metadata.globalCounts&&a.metadata.globalCounts.count!=k){var c=a.metadata.globalCounts.count,d=b.f.R("aggregateCount");if(d){var e;e=(e="en-US".match(/^\w{2,3}([-_]|$)/))?e[0].replace(/[_-]/g,""):"";var f;f=b.Gb;if("en"!=e){var g=c;if(isNaN(g))f=U.Fb;else{var h=[],j=0>g||0==g&&0>1/g;h.push(j?f.m:f.z);if(isFinite(g))if(g*=j?-1:1,g*=f.g,f.u)if(0==g)ze(f,g,f.b,h),Ae(f,0,h);else{var n=Math.floor(Math.log(g)/Math.log(10)),g=g/Math.pow(10,n),p=f.b;if(1<f.i&&f.i>f.b){for(;0!=
n%f.i;)g*=10,n--;p=1}else 1>f.b?(n++,g/=10):(n-=f.b-1,g*=Math.pow(10,f.b-1));ze(f,g,p,h);Ae(f,n,h)}else ze(f,g,f.b,h);else h.push(U.Cb);h.push(j?f.q:f.A);f=h.join("")}}else f=Math.floor(10*c),1E7<=f?f/=1E6:1E4<=f&&(f/=1E3),f=Math.floor(f),f=10<=f&&100>f&&0!=f%10?""+(f/10).toPrecision(2):""+Math.floor(f/10);e={count:f,Q:c.toString().length,lang:e};h="";h="en"==e.lang?9<e.Q?h+"Lots":6<e.Q?h+(V(e.count)+"M"):3<e.Q?h+(V(e.count)+"k"):h+V(e.count):4<e.Q?h+"10K+":h+V(e.count);d.innerHTML=h;!b.i.b.PA&&b.f.R("aggregateBubble").setAttribute("title",
He({count:f,Q:c.toString().length}))}}if(a){c=Lb("checked",b.f.b);d=Lb("unchecked",b.f.b);if(c&&d){for(e=0;e<c.length;e++)c[e].style.display=a.isSetByViewer?"":"none";for(e=0;e<d.length;e++)d[e].style.display=!a.isSetByViewer?"":"none"}n=b.i.q;c=b.i.l;d=b.i.m;if(n||c)e=b.f.R("widget_bounds"),f=e.style,h=f.display,j=f.whiteSpace,f.display="inline-block",f.whiteSpace="nowrap",g={},n&&(n=e.offsetWidth+1,g.width=d?Math.min(n,d):n),c&&(g.height=e.offsetHeight),iframes.resize(g),f.display=h,f.whiteSpace=
j}}function Ye(b,a){var c=b.f.R("plusone");if(c){var d;if(b.L){d="yT";b.m.setAttribute("title","+1");try{b.b.K(l,l)}catch(e){c.className=d,i(e)}}else b.d.b(b.g).get()&&Ze(b)?(d="Or",b.A=H()+650):(a.isSetByViewer?(d="Qi",b.m.setAttribute("aria-pressed","true")):(d="Sh",b.m.setAttribute("aria-pressed","false")),Ne(b,a));c.className=d}}function Ne(b,a){var c=b.fb(!!a&&a.isSetByViewer,b.fa,b.ga);Re(b)||Pe(b)?b.m.setAttribute("aria-label",c):b.m.setAttribute("title",c)}
function af(b){if(!b.u&&!ba(b.Ha.get("BEAT"))||!b.l.b){var a=xd(b.f);if(a.iframer&&a.iframer.onpopup)a.iframer.onpopup();b.la=l;Qc(b.l,xd(b.f));return l}return o}function bf(b){if(!b.L)return o;(b=Rc())&&b.focus();return l}function cf(b,a){var c=parseInt(a,10);if(c==a)return""+c}function df(b,a){var c=xd(b.f);if(c.iframer&&c.iframer.onPlusOne)c.iframer.onPlusOne({state:a?"on":"off",href:b.g})}
function Ze(b){var a=b.g,c=Cc(b.d,a),d;if(!(d=!!b.A))if(!(d=!!c.d.length)){if(c=!!c.b)c=!b.d.b(a).d;d=c}return d}function ef(b,a){return x(function(){try{a.apply(this,arguments)}catch(b){try{b.errsource="plusone_publisher",this.Vb(b)}catch(d){}}},b)}function Re(b){return b.X&&!!b.i.b.UC&&!!iframes.getHandler("bubble")}function Pe(b){return b.X&&!!b.i.b.UH&&!!iframes.getHandler("bubble")}
function ff(b){var a=b.get("na").d||"widget",c=b.get("ia"),c=x(c.hb,c),a=new Oc(a,1);a.d=c;a.g=l;(c=xd(vd(document)).__P1_BASEURL)&&Pc(a,c);Wd(b,"ja",a)}var wd;ud.prototype.R=function $sa(a){return w(a)?this.b.getElementById(a):a};ud.prototype.createElement=function $ta(a){return this.b.createElement(a)};
ud.prototype.contains=function $ua(a,c){if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||Boolean(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};var zd={},gf=[1,4,2],Ue=[];r=Ed.prototype;r.O=function $va(){return this.p.O()};r.Ja=function $wa(a){for(var a=Rb(a),c=a.length,d=0;d<c;d++){var e=a[d];this.p.set(Cd(e),e)}};r.remove=function $xa(a){return this.p.remove(Cd(a))};
r.contains=function $ya(a){a=Cd(a);return Ob(this.p.p,a)};r.F=function $za(){return this.p.F()};r.P=function $Aa(){return new Ed(this)};
r.Na=function $Ca(a){var c;if(c=this.O()==Bd(a)){var d=a,a=Bd(d);if(this.O()>a)c=o;else{!(d instanceof Ed)&&5<a&&(d=new Ed(d));b:if(a=function $Ba(a){if("function"==typeof d.contains)a=d.contains(a);else if("function"==typeof d.wa)a=d.wa(a);else if(u(d)||w(d))a=A(d,a);else a:{for(var c in d)if(d[c]==a){a=l;break a}a=o}return a},"function"==typeof this.every)c=this.every(a,k);else if(u(this)||w(this))c=Qa(this,a,k);else{c=Qb(this);for(var e=Rb(this),f=e.length,g=0;g<f;g++)if(!a.call(k,e[g],c&&c[g], this)){c=o;break b}c=l}}}return c};r.Ia=function $Da(){return this.p.Ia(o)};var Te=o,Ve=[];Kd.prototype.toString=function $Ea(){return this.b.toString()};L(G.k(),"sy5");
y(Qd,Kd);y(Rd,Kd);y(ae,E);ae.prototype.get=function $Fa(a){var c=Vd(this,a);c||i(new ee(a));return c};ae.prototype.v=function $Ga(){if(be(this)==this){var a=this.i;if(a)for(;a.length;)a[0].N()}else for(var a=be(this).i,c=0;c<a.length;c++)if(a[c]==this){a.splice(c,1);break}for(var d in this.d)a=this.d[d],a[1]&&"undefined"!=typeof a[0].N&&a[0].N();this.d=m;this.A&&this.q.N();var e=this;this.b&&Wb(this.b,function(a,c,d){Pd(a,function(c){c.T==e&&ma(a,c)});0==a.length&&delete d[c]});this.b=m;F(this.z);this.u=this.z=m;ae.H.v.call(this)}; y(ee,z);
T.prototype.d=o;T.prototype.q=function $Ha(){this.b&&(this.b=m,ie(this.g));this.d=o};T.prototype.u=function $Ia(a){this.d!=a&&(a?ge(this.g):ie(this.g));this.d=a};T.prototype.m=function $Ja(a){this.b&&this.b.showSpinner&&this.b.showSpinner(a)};y(me,T);y(oe,T);y(pe,S);r=pe.prototype;r.jc=200;r.Z=o;r.ma=0;r.Ma=3E3;r.ib=1E3;r.gc=function $Ka(){this.ma=H();this.Z=o;this.d||(this.d=Id(x(this.ec,this),this.jc))};r.ec=function $La(){if(!this.m){var a=Ad(this.Ha,this.q),a=!(!a||!a.isSetByViewer);if(!this.m&&this.ga&&!this.Z&&!(this.g&&this.g.d||this.i&&this.i.d))this.b&&!this.b.d&&this.b.b?se(this,l):(a=this.pb(this.D,x(this.qb,this),this.fa,this.q,a,this.f,this.L,this.ua,this.ta,this.A),qe(this,a),this.b=this.i=a,this.z=this.ib)}};
r.fc=function $Ma(){this.ma=H();te(this);this.d&&(td.clearTimeout(this.d),this.d=k)};r.ob=function $Na(a,c,d,e,f,g,h){return new me(a,c,d,e,f,g,m,h)};r.pb=function $Oa(a,c,d,e,f,g,h,j,n,p){return new oe(a,c,d,e,f,g,h,j,n,p)};r.qb=function $Pa(a){this.ma<a.timestamp&&(this.ma=a.timestamp,"mouseover"==a.type?this.Z=o:"mouseout"==a.type&&te(this))};
r.K=function $Qa(a,c){var d=this.b;if(d&&(d.d||d.b))a?(!this.A||c?(d.b&&(d.b.close?d.b.close():d.b=m),d.d=o,this.i=this.g=this.b=m,this.ma=0):ke(d,o),this.Z=o,this.l&&td.clearTimeout(this.l)):te(this)};r.Qb=function $Ra(){if(this.Z){var a=this.b;if(a&&(a=le(a,"canAutoClose"))){a(x(this.K,this));return}this.K(l)}};r.v=function $Sa(){this.K(l);this.b=this.i=m;this.d&&(td.clearTimeout(this.d),this.d=k);pe.H.v.call(this)};
var Qe=["top","right","bottom","left"];var Oe=new ue,hf=["click",Za?"keypress":"keydown"];ue.prototype.b=function $Ta(a,c,d,e,f){function g(a){if("click"==a.type&&(vb?0==a.ha.button:"click"==a.type||a.ha.button&gf[0])&&(!ab||!cb||!a.ctrlKey))c.call(e,a);else if(13==a.keyCode||3==a.keyCode)a.type="keypress",c.call(e,a)}g.b=c;g.d=e;f?oc(f,a,hf,g):Jb(a,hf,g)};
var xe={AED:[2,"dh","\u062f.\u0625.","DH"],AUD:[2,"$","AU$"],BDT:[2,"\u09f3","Tk"],BRL:[2,"R$","R$"],CAD:[2,"$","C$"],CHF:[2,"CHF","CHF"],CLP:[0,"$","CL$"],CNY:[2,"\u00a5","RMB\u00a5"],COP:[0,"$","COL$"],CRC:[0,"\u20a1","CR\u20a1"],CZK:[2,"K\u010d","K\u010d"],DKK:[18,"kr","kr"],DOP:[2,"$","RD$"],EGP:[2,"\u00a3","LE"],EUR:[18,"\u20ac","\u20ac"],GBP:[2,"\u00a3","GB\u00a3"],HKD:[2,"$","HK$"],ILS:[2,"\u20aa","IL\u20aa"],INR:[2,"\u20b9","Rs"],ISK:[0,"kr","kr"],JMD:[2,"$","JA$"],JPY:[0,"\u00a5","JP\u00a5"],
KRW:[0,"\u20a9","KR\u20a9"],LKR:[2,"Rs","SLRs"],MNT:[0,"\u20ae","MN\u20ae"],MXN:[2,"$","Mex$"],MYR:[2,"RM","RM"],NOK:[18,"kr","NOkr"],PAB:[2,"B/.","B/."],PEN:[2,"S/.","S/."],PHP:[2,"\u20b1","Php"],PKR:[0,"Rs","PKRs."],RUB:[2,"Rup","Rup"],SAR:[2,"Rial","Rial"],SEK:[2,"kr","kr"],SGD:[2,"$","S$"],THB:[2,"\u0e3f","THB"],TRY:[2,"TL","YTL"],TWD:[2,"NT$","NT$"],USD:[2,"$","US$"],UYU:[2,"$","UY$"],VND:[0,"\u20ab","VN\u20ab"],YER:[0,"Rial","Rial"],ZAR:[2,"R","ZAR"]};
var jf={yb:".",Bb:",",Ib:"%",Xa:"0",Lb:"+",Db:"-",Ab:"E",Kb:"\u2030",Cb:"\u221e",Fb:"NaN",xb:"#,##0.###",Nb:"#E0",Jb:"#,##0%",wb:"\u00a4#,##0.00;(\u00a4#,##0.00)",zb:"USD"},U=jf,U=jf;var De=/\s*;\s*/;r=Be.prototype;r.set=function $Ua(a,c,d,e,f,g){/[;=\s]/.test(a)&&i(Error("N`"+a));/[;\r\n]/.test(c)&&i(Error("O`"+c));ba(d)||(d=-1);f=f?";domain="+f:"";e=e?";path="+e:"";g=g?";secure":"";d=0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(H()+1E3*d)).toUTCString();this.b.cookie=a+"="+c+f+e+d+g};r.get=function $Va(a,c){for(var d=a+"=",e=(this.b.cookie||"").split(De),f=0,g;g=e[f];f++){if(0==g.indexOf(d))return g.substr(d.length);if(g==a)return""}return c};
r.remove=function $Wa(a,c,d){var e=ba(this.get(a));this.set(a,"",0,c,d);return e};r.U=function $Xa(){return Ce(this).keys};r.F=function $Ya(){return Ce(this).vb};r.O=function $Za(){return!this.b.cookie?0:(this.b.cookie||"").split(De).length};r.wa=function $_a(a){for(var c=Ce(this).vb,d=0;d<c.length;d++)if(c[d]==a)return l;return o};
J&&N(8);var Ge={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Ee=/[\x00\x22\x26\x27\x3c\x3e]/g;
var kf;y(Je,Ie);kf=new Je;Le.prototype.hb=function $0a(a){try{var c={};c["call-stack"]=Nd();var d;var e=Fb("window.location.href");if(w(a))d={message:a,name:"Unknown error",lineNumber:"Not available",fileName:e,stack:"Not available"};else{var f,g,h=o;try{f=a.lineNumber||a.b||"Not available"}catch(j){f="Not available",h=l}try{g=a.fileName||a.filename||a.sourceURL||e}catch(n){g="Not available",h=l}d=h||!a.lineNumber||!a.fileName||!a.stack?{message:a.message,name:a.name,lineNumber:f,fileName:g,stack:a.stack||"Not available"}:
a}var p=d.stack,q=Md(this.b,"script",d.fileName,"error",d.message,"line",d.lineNumber),a={};a.trace=p;if(c)for(var v in c)a["context."+v]=c[v];var C=mc([],a);C[0]="";var W=C.join(""),B,sb;a:{if(!kf.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(p=0;p<c.length;p++){var Ke=c[p];try{new ActiveXObject(Ke);sb=kf.b=Ke;break a}catch(vg){}}i(Error("R"))}sb=kf.b}B=sb?new ActiveXObject(sb):new XMLHttpRequest; B.open("POST",q,l);B.setRequestHeader("Content-type","application/x-www-form-urlencoded");B.setRequestHeader("Content-length",W.length.toString());B.send(W)}catch(wg){}};
y(Me,S);r=Me.prototype;r.la=o;r.bc=function $1a(a){if(!this.La(a,l)){if(!this.u||this.l.b!=a.signedUp)this.b.f=H();this.u=l;this.l.b=a.signedUp;var c=a.displayName;this.ga=a.email||"";this.fa=c||"";Ne(this,Ad(this.d,this.g));this.la&&(this.Ca(),this.la=o)}};r.ba=function $2a(){this.b.f=H();if(this.A){var a=this.A-H();if(0<a){xd(this.f).setTimeout(x(this.ba,this),a);return}this.A=0}((a=Ad(this.d,this.g))||this.L)&&this.Ua(a)};
r.Ua=function $3a(a){!a.isSetByViewer&&(this.b.b&&this.b.b.d)&&this.b.K(l,l);Xe(this,a);Ye(this,a)};
r.fb=function $4a(a,c,d){c={Ka:a,M:c,B:d};a="";c.Ka?c.M&&c.B?(c="You publicly +1'd this as "+(V(c.M)+(" ("+(V(c.B)+"). Click again to undo."))),a+=c):c.B?(c="You publicly +1'd this as "+(V(c.B)+". Click again to undo."),a+=c):a+="You publicly +1'd this. Click again to undo.":c.M&&c.B?(c="Click here to publicly +1 this as "+(V(c.M)+(" ("+(V(c.B)+")."))),a+=c):c.B?(c="Click here to publicly +1 this as "+(V(c.B)+"."),a+=c):a+="Click here to publicly +1 this.";return a};r.qc=function $5a(a){this.ra.b.push(new Qd(a))};
r.Ca=function $6a(){if(!Ze(this)&&!af(this)&&!bf(this)){var a=this.g,c=Ad(this.d,a);if(c&&2!=Ac(Cc(this.d,a),x(c.isSetByViewer?this.Ea:this.sc,this)))c.isSetByViewer?xd(this.f).setTimeout(x(this.ba,this),150):(c=this.b,!c.m&&c.ra&&(a=new ne(c.D,c.q,c.f,c.L),c.u&&(a.d.referer=c.u),c=a.b instanceof hc?a.b.P():new hc(a.b,k),c.b.Zb(a.d),(a=Fc(c,a.f))&&a.focus()))}};
r.Pa=function $7a(){if(!this.u||this.l.b)this.b.f=H();this.u=l;this.b.K(l,l);this.l.b?Dc(this.d,this.d.d.getSignupState({source:this.i.d,nolog:l})).execute(ef(this,this.bc)):this.la&&(this.Ca(),this.la=o)};
r.sc=function $8a(){var a=Ad(this.d,this.g);if(a&&!a.isSetByViewer){var a=We(this,{optimistic:l,cdx:(H()-this.sa).toString(16),profileVersion:this.l.i||k}),c=this.i.g;c&&(a.abtk=c);this.q&&(a.ad=this.q);this.D.cr&&(a.cr=cf(this,this.D.cr));this.D.ag&&(a.ag=cf(this,this.D.ag));this.b.K(l,l);re(this.b);Dc(this.d,this.d.d.insert(a)).execute(ef(this,this.La));df(this,l)}};
r.Ea=function $9a(){var a=Ad(this.d,this.g);a&&a.isSetByViewer&&(a=We(this,{cdx:(H()-this.sa).toString(16),profileVersion:this.l.i||k}),this.q&&(a.ad=this.q),this.d.remove(a).execute(ef(this,this.La)),df(this,o));this.b.K(l,l)};r.La=function $$a(a,c){var d=Zd(a,this.ta?this.ta.b:k,this.ta);c||(this.L=d,this.b.m=!!d,this.ba());d&&this.b.K(l,l);return d};r.v=function $ab(){this.d=this.z=m;Me.H.v.call(this)};r.nb=function $bb(a,c,d,e,f,g,h,j,n,p,q,v){return new pe(a,c,d,e,f,g,h,j,n,p,l,q,v)}; r.getId=aa("g");r.xc=function $db(a){return this.g==a};

M(G.k(),"sy5");K(G.k(),"sy5");
}catch(e){_DumpException(e)}
try{
function lf(b){Me.call(this,b)}function mf(b){b=Se(b);ff(b);new lf(b);return b}L(G.k(),"sy7");y(lf,Me);
M(G.k(),"sy7");K(G.k(),"sy7");
}catch(e){_DumpException(e)}
try{
L(G.k(),"p1p");mf();
M(G.k(),"p1p");K(G.k(),"p1p");
}catch(e){_DumpException(e)}

// Copyright 2002-2012 Google Inc.
